//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinmaya.Registration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardPayment
    {
        public int InvoiceId { get; set; }
        public int StatusId { get; set; }
        public string UserId { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDonate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
