//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinmaya.Registration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public int RelationshipId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public int GenderId { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
