//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinmaya.Registration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedAccount
    {
        public int ID { get; set; }
        public string To_UserId { get; set; }
        public string From_UserId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeclined { get; set; }
        public Nullable<bool> IsDeclinedPermanently { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
