//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinmaya.Registration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecurityQuestion
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int SecurityQuestionId { get; set; }
        public string Answer { get; set; }
    }
}
